name: ffmpeg-api container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - './**'
      - '!**.adoc'
jobs:
  ffmpeg-api-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: elpe21/ffmpeg-api
      tagname: $GITHUB_REF_NAME
      dockerfile: ./Dockerfile
      directory: .
    secrets: inherit
